# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Test
    steps:
      - task: Docker@2
        displayName: Build and Push image
        inputs:
          containerRegistry: 'Docker Hub Connection'
          repository: 'k8sExample'
          command: 'buildAndPush'
          Dockerfile: '**/KubernetesExample/Dockerfile'
